
/**:
  ros__parameters:
    use_sim_time: true

    frame_id: "base_footprint"
    odom_frame_id: "odom"
    map_frame_id: "map"
    publish_tf: true

    subscribe_rgbd: true
    subscribe_scan_cloud: true
    subscribe_odom_info: false

    approx_sync: true
    approx_sync_max_interval: 0.1
    sync_queue_size: 30
    topic_queue_size: 30
    wait_for_transform: 0.2

    Reg/Strategy: "2"
    Reg/Force3DoF: "true"

    Icp/PointToPlane: "true"
    Icp/MaxCorrespondenceDistance: "0.5"
    Icp/VoxelSize: "0.05"
    Icp/Iterations: "10"
    Icp/Epsilon: "0.001"

    RGBD/ProximityBySpace: "true"
    RGBD/ProximityPathMaxNeighbors: "1"
    RGBD/AngularUpdate: "0.05"
    RGBD/LinearUpdate: "0.05"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/NeighborLinkRefining: "true"

    Grid/Sensor: "0"
    Grid/FromDepth: "false"
    Grid/3D: "true"
    Grid/RangeMax: "4.0"
    Grid/RangeMin: "0.5"
    Grid/RayTracing: "true"
    Grid/CellSize: "0.05"
    Grid/MinGroundHeight: "-0.05"
    Grid/MaxGroundHeight: "0.05"
    Grid/MaxObstacleHeight: "2.5"
    Grid/NormalsSegmentation: "false"

    Optimizer/Strategy: "1"
    Optimizer/Robust: "true"

    Mem/UseOdomFeatures: "true"
    Mem/STMSize: "30"
    Mem/NotLinkedNodesKept: "false"
    Mem/DepthCompressionFormat: ".png"
